# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib soccerrsr, .registration = TRUE
NULL

soccer_net <- function(df, n, block_size) .Call(wrap__soccer_net, df, n, block_size)

clips <- function(df, n, block_size) .Call(wrap__clips, df, n, block_size)

embed_job <- function(text1, text2) .Call(wrap__embed_job, text1, text2)

embed_jobs <- function(text1, text2) .Call(wrap__embed_jobs, text1, text2)

# nolint end
